### ISSUE TITLE
Faster `parse_unique_mutations` function

### ISSUE THREAD

**Issue by DBecker7** [DASL-Lab/provoc#4]
It's slow. Make it not slow.

[Link to relevant function.](https://github.com/DASL-Lab/provoc/blob/cc6014d44ae350f1b8767493e5691ae2f61cb44f/R/parse_mutations.R#L96) It may be worthwhile to modify the way `parse_mutation` works. Note that `parse_mutations` is the only function that's exported, so modifying the other functions shouldn't break any existing code.

**Comment by danerkestey** [comment]
I will begin by profiling the parse_mutations function to identify any performance bottlenecks. Possible optimizations might include reusing computed results to avoid repeated calculations, or rethinking data structure usage for faster access. Since parse_mutations is the only exported function, I'll ensure any internal changes do not affect the public API. After optimization, I'll test for both improved speed and maintained functionality.

There are nested loops in `parse_unique_mutations` and string operations within loops which could lead to worse performance.
